downgrade devtools-frontend rollup4 to rollup3
We delete all *.wasm binary blobs, but the devtools-frontend rollup4
upgrade used @rollup/wasm-node/ that depended on a *.wasm blob:

RuntimeError: Command '/chromium-132.0.6834.83/out/Release/../../third_party/node/linux/node-linux-x64/bin/node ../../third_party/devtools-frontend/src/node_modules/@rollup/wasm-node/dist/bin/rollup --silent --config ../../third_party/devtools-frontend/src/scripts/build/rollup.config.mjs --input gen/third_party/devtools-frontend/src/front_end/third_party/lit/lit.prebundle.js --file gen/third_party/devtools-frontend/src/front_end/third_party/lit/lit.js' failed
node:fs:573
  return binding.open(
                 ^

Error: ENOENT: no such file or directory, open '/chromium-132.0.6834.83/third_party/devtools-frontend/src/node_modules/@rollup/wasm-node/dist/wasm-node/bindings_wasm_bg.wasm'

Rather than dealing with that, we switched to using the packaged rollup
(which is still at 3.29.x in sid rather than 4.x); this time a symlink
to /usr/share/nodejs/*rollup* rather than copying files over.